-- MASTER SETUP SCRIPT v2 (Updated for Demo RPC + Auth Logic)
-- Run this in your new Supabase Project SQL Editor

-- 1. REGISTRY TABLE (For Bin ID Verification)
create table if not exists public.r3bin_registry (
    id bigint generated by default as identity primary key,
    bin_id text not null unique,
    location text,
    status text default 'normal',
    created_at timestamptz default now()
);

alter table public.r3bin_registry enable row level security;
create policy "Public read registry" on r3bin_registry for select using (true);
-- Allow authenticated insert if needed, but usually admin only.

-- 2. WASTE LOGS TABLE (For Dashboard Data)
create table if not exists public.r3bin_waste_logs (
    id bigint generated by default as identity primary key,
    bin_id text not null references public.r3bin_registry(bin_id),
    waste_type text not null,
    weight float,
    updated_at timestamptz default now()
);

alter table public.r3bin_waste_logs enable row level security;
create policy "Authenticated read logs" on r3bin_waste_logs for select to authenticated using (true);
create policy "Service role write logs" on r3bin_waste_logs for insert to service_role with check (true);

-- 3. CONTACT MESSAGES (For Schedule Demo)
create table if not exists public.contact_messages (
    id bigint generated by default as identity primary key,
    name text,
    email text,
    phone text,
    message text,
    created_at timestamptz default now()
);

alter table public.contact_messages enable row level security;
create policy "Public insert contact" on contact_messages for insert to public with check (true);

-- 4. RPC FUNCTION for CONTACT MESSAGES (Required by Frontend)
create or replace function public.insert_contact_message(
    p_name text,
    p_phone text,
    p_email text,
    p_message text default ''
)
returns json
language plpgsql
security definer
as $$
declare
  new_id bigint;
begin
  insert into public.contact_messages (name, email, phone, message)
  values (p_name, p_email, p_phone, p_message)
  returning id into new_id;
  
  return json_build_object('success', true, 'id', new_id);
end;
$$;

-- 5. USER BINS TABLE (For Linking Users to Bins)
create table if not exists public.user_bins (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  bin_id text not null,
  created_at timestamptz default now(),
  unique (user_id, bin_id)
);

alter table public.user_bins enable row level security;
create policy "Users view own bins" on user_bins for select using (auth.uid() = user_id);
create policy "Users insert own bins" on user_bins for insert with check (auth.uid() = user_id);

-- 6. AUTH TRIGGER (Handle Signups & Linking)
create or replace function public.handle_new_user()
returns trigger as $$
declare
  bin_id_target text;
begin
  -- Extract bin_id from metadata
  bin_id_target := new.raw_user_meta_data->>'bin_id';

  -- RESTRICTION: Block Google Signups if no Bin ID (implies they must use Signup form)
  -- BUT since we want to allow Google Sign In for EXISTING users, we check inserts.
  -- Valid Signup (via form) provides 'bin_id' in metadata.
  -- Invalid Signup (via Google direct) has no 'bin_id'.
  if bin_id_target is null or char_length(bin_id_target) = 0 then
    raise exception 'Please sign up via the registration page first.';
  end if;

  -- LINKING: If we get here, bin_id exists. Link it.
  insert into public.user_bins (user_id, bin_id)
  values (new.id, bin_id_target)
  on conflict (user_id, bin_id) do nothing;

  return new;
end;
$$ language plpgsql security definer;

-- Trigger checks (Drop old ones first to be safe)
drop trigger if exists on_auth_user_created on auth.users;
drop trigger if exists on_auth_user_creation_check on auth.users;

-- Keep trigger on AFTER INSERT so user exists for foreign key referenec in user_bins
-- Exception in AFTER trigger rolls back everything seamlessly.
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();

-- 7. SEED DATA
insert into public.r3bin_registry (bin_id, location, status)
values ('bin_001', 'Main Campus', 'normal')
on conflict (bin_id) do nothing;

-- 8. PERMISSIONS
grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;
