-- Backend setup for "Schedule Demo" feature

-- 1. Create table for storing demo requests (if it doesn't exist)
create table if not exists public.contact_messages (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    phone text not null,
    message text,
    created_at timestamptz default now()
);

-- 2. Enable Row Level Security (RLS)
alter table public.contact_messages enable row level security;

-- 3. Create a policy to allow public inserts (since user isn't logged in yet)
-- This allows anyone to submit the form, but they can't see the data.
create policy "Public insert contact" on public.contact_messages
for insert to public
with check (true);

-- 4. Create the Custom Function (RPC) called by the frontend
-- The frontend code calls: supabase.rpc('insert_contact_message', { ... })
create or replace function public.insert_contact_message(
    p_name text,
    p_phone text,
    p_email text,
    p_message text default ''
)
returns json
language plpgsql
security definer -- Runs with elevated privileges to ensure insert works regardless of RLS quirks
as $$
declare
  new_id bigint;
begin
  insert into public.contact_messages (name, email, phone, message)
  values (p_name, p_email, p_phone, p_message)
  returning id into new_id;
  
  return json_build_object('success', true, 'id', new_id);
end;
$$;

-- 5. Grant permissions to anonymous users so the landing page can call it
grant usage on schema public to anon, authenticated;
grant all on public.contact_messages to anon, authenticated;
grant execute on function public.insert_contact_message to anon, authenticated;
