
-- 1. CLEANUP (Optional, careful with production data)
-- drop table if exists r3bin_registry cascade;
-- drop table if exists r3bin_waste_logs cascade;
-- drop table if exists contact_messages cascade;

-- 2. CREATE REGISTRY TABLE (For Bin ID Verification)
create table if not exists public.r3bin_registry (
    id bigint generated by default as identity primary key,
    bin_id text not null unique,
    location text,
    status text default 'normal',
    created_at timestamptz default now()
);

-- Enable RLS
alter table public.r3bin_registry enable row level security;
create policy "Public read registry" on r3bin_registry for select using (true);
create policy "Authenticated read registry" on r3bin_registry for select to authenticated using (true);


-- 3. INSERT DEFAULT BIN (Crucial for Signup Verification)
insert into public.r3bin_registry (bin_id, location, status)
values ('bin_001', 'Main Campus', 'normal')
on conflict (bin_id) do nothing;


-- 4. CREATE WASTE LOGS TABLE (For Dashboard Data)
create table if not exists public.r3bin_waste_logs (
    id bigint generated by default as identity primary key,
    bin_id text not null references public.r3bin_registry(bin_id),
    waste_type text not null, -- 'plastic', 'metal', 'paper', 'mixed'
    weight float, -- Optional if just counting items
    updated_at timestamptz default now()
);

-- Enable RLS
alter table public.r3bin_waste_logs enable row level security;
create policy "Authenticated read logs" on r3bin_waste_logs for select to authenticated using (true);
create policy "Service role write logs" on r3bin_waste_logs for insert to service_role with check (true);


-- 5. CREATE CONTACT MESSAGES
create table if not exists public.contact_messages (
    id bigint generated by default as identity primary key,
    name text,
    email text,
    phone text,
    message text,
    created_at timestamptz default now()
);

alter table public.contact_messages enable row level security;
create policy "Public insert contact" on contact_messages for insert to public with check (true);


-- 6. ENSURE USER BINS EXISTS (For User-Bin Linking)
create table if not exists public.user_bins (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  bin_id text not null,
  created_at timestamptz default now(),
  unique (user_id, bin_id)
);

alter table public.user_bins enable row level security;
create policy "Users view own bins" on user_bins for select using (auth.uid() = user_id);
create policy "Users insert own bins" on user_bins for insert with check (auth.uid() = user_id);

-- 7. RE-SEED PROFILES (Just in case)
-- This relies on the trigger working for new users.

-- 8. PERMISSIONS
grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;
